# Generated by Django 5.1.3 on 2024-12-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricsModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('TTrvT', models.FloatField()),
                ('TTrvD', models.FloatField()),
                ('TTrvAS', models.FloatField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('radius', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StayPointModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('spId', models.IntegerField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('arvT', models.FloatField()),
                ('levT', models.FloatField()),
                ('visitTime', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TraceModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('time', models.FloatField()),
                ('spId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TravelsModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('arvId', models.IntegerField()),
                ('levId', models.IntegerField()),
                ('TrvD', models.FloatField()),
                ('TrvT', models.FloatField()),
                ('TrvAS', models.FloatField()),
            ],
        ),
    ]
