# Generated by Django 5.1.3 on 2024-12-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_metricsmodel_entityid_staypointmodel_entityid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entityId', models.IntegerField()),
                ('spId', models.IntegerField()),
                ('arvT', models.IntegerField()),
                ('levT', models.IntegerField()),
                ('visitT', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='staypointmodel',
            name='arvT',
        ),
        migrations.RemoveField(
            model_name='staypointmodel',
            name='entityId',
        ),
        migrations.RemoveField(
            model_name='staypointmodel',
            name='levT',
        ),
        migrations.RemoveField(
            model_name='staypointmodel',
            name='visitTime',
        ),
        migrations.AddField(
            model_name='staypointmodel',
            name='numVisits',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
