# Generated by Django 5.1.3 on 2024-12-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_visitmodel_remove_staypointmodel_arvt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staypointmodel',
            name='entropy',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
