# Generated by Django 5.1.3 on 2024-12-09 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_staypointmodel_entropy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('totalVisits', models.IntegerField()),
                ('metrics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metrics.metricsmodel')),
                ('stayPoint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metrics.staypointmodel')),
                ('trace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metrics.tracemodel')),
                ('travel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metrics.travelsmodel')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metrics.visitmodel')),
            ],
        ),
    ]
