# Generated by Django 5.1.3 on 2024-12-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_configmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configmodel',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='metricsmodel',
            old_name='x',
            new_name='x_center',
        ),
        migrations.RenameField(
            model_name='metricsmodel',
            old_name='y',
            new_name='y_center',
        ),
        migrations.RenameField(
            model_name='metricsmodel',
            old_name='z',
            new_name='z_center',
        ),
        migrations.RemoveField(
            model_name='configmodel',
            name='totalVisits',
        ),
        migrations.AddField(
            model_name='configmodel',
            name='distanceThreshold',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configmodel',
            name='radiusThreshold',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configmodel',
            name='timeThreshold',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
