# Generated by Django 5.1.3 on 2024-12-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0006_rename_nome_configmodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricsmodel',
            name='fileName',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staypointmodel',
            name='fileName',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracemodel',
            name='fileName',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelsmodel',
            name='fileName',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitmodel',
            name='fileName',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ConfigModel',
        ),
    ]
