# Generated by Django 5.1.3 on 2024-12-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0007_metricsmodel_filename_staypointmodel_filename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.TextField()),
                ('id1', models.IntegerField()),
                ('id2', models.IntegerField()),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('start_x_id_1', models.FloatField()),
                ('start_x_id_2', models.FloatField()),
                ('start_y_id_1', models.FloatField()),
                ('start_y_id_2', models.FloatField()),
                ('start_z_id_1', models.FloatField()),
                ('start_z_id_2', models.FloatField()),
                ('end_x_id_1', models.FloatField()),
                ('end_x_id_2', models.FloatField()),
                ('end_y_id_1', models.FloatField()),
                ('end_y_id_2', models.FloatField()),
                ('end_z_id_1', models.FloatField()),
                ('end_z_id_2', models.FloatField()),
            ],
        ),
    ]
