# Generated by Django 5.1.3 on 2025-01-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0008_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.TextField()),
                ('label', models.TextField()),
                ('distanceThreshold', models.FloatField()),
                ('timeThreshold', models.FloatField()),
                ('radiusThreshold', models.FloatField()),
            ],
        ),
    ]
