# Generated by Django 5.1.3 on 2025-01-27 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0009_configmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TraceModel',
        ),
    ]
