# Generated by Django 5.1.3 on 2025-02-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0010_delete_tracemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricsmodel',
            name='avgTimeVisit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metricsmodel',
            name='avg_travel_avg_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metricsmodel',
            name='avg_travel_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metricsmodel',
            name='avg_travel_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metricsmodel',
            name='numStayPointsVisits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metricsmodel',
            name='num_travels',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
