# Generated by Django 5.1.3 on 2025-02-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0011_metricsmodel_avgtimevisit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricsmodel',
            name='label',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
