# Generated by Django 5.1.3 on 2025-02-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0012_metricsmodel_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='end_time',
            new_name='contact_timestamp',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='start_time',
        ),
    ]
