# Generated by Django 5.1.3 on 2025-03-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0013_rename_end_time_contactmodel_contact_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configmodel',
            name='quadrantSize',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
