# Generated by Django 5.1.3 on 2025-03-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0014_configmodel_quadrantsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuadrantEntropyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.TextField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('z', models.IntegerField()),
                ('entropy', models.IntegerField()),
            ],
        ),
    ]
