# Generated by Django 5.1.3 on 2025-03-11 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0015_quadrantentropymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quadrantentropymodel',
            name='z',
        ),
    ]
