# Generated by Django 5.1.3 on 2025-03-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0016_remove_quadrantentropymodel_z'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quadrantentropymodel',
            name='entropy',
            field=models.FloatField(),
        ),
    ]
