# Generated by Django 5.1.3 on 2025-03-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0017_alter_quadrantentropymodel_entropy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricsmodel',
            name='label',
            field=models.TextField(),
        ),
    ]
