# Generated by Django 5.1.3 on 2025-04-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0018_alter_metricsmodel_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalMetricsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.TextField()),
                ('label', models.TextField()),
                ('avgTTrvT', models.FloatField()),
                ('avgTTrvD', models.FloatField()),
                ('avgTTrvAS', models.FloatField()),
                ('avgX_center', models.FloatField()),
                ('avgY_center', models.FloatField()),
                ('avgZ_center', models.FloatField()),
                ('avgRadius', models.FloatField()),
                ('numStayPoints', models.IntegerField()),
                ('avgNumStayPointsVisitsPerEtity', models.FloatField()),
                ('NumStayPointsVisits', models.IntegerField()),
                ('avgStayPointEntropy', models.FloatField()),
                ('avgQuadrantEntropy', models.FloatField()),
                ('numContacts', models.IntegerField()),
                ('num_travels', models.IntegerField()),
                ('avg_travel_time', models.FloatField()),
                ('avg_travel_distance', models.FloatField()),
                ('avg_travel_avg_speed', models.FloatField()),
            ],
        ),
    ]
