# Generated by Django 5.0.6 on 2025-04-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0019_globalmetricsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadrantentropymodel',
            name='visit_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
