# Generated by Django 5.0.6 on 2025-04-05 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0020_quadrantentropymodel_visit_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='end_x_id_1',
            new_name='x_id_1',
        ),
        migrations.RenameField(
            model_name='contactmodel',
            old_name='end_x_id_2',
            new_name='x_id_2',
        ),
        migrations.RenameField(
            model_name='contactmodel',
            old_name='end_y_id_1',
            new_name='y_id_1',
        ),
        migrations.RenameField(
            model_name='contactmodel',
            old_name='end_y_id_2',
            new_name='y_id_2',
        ),
        migrations.RenameField(
            model_name='contactmodel',
            old_name='end_z_id_1',
            new_name='z_id_1',
        ),
        migrations.RenameField(
            model_name='contactmodel',
            old_name='end_z_id_2',
            new_name='z_id_2',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='start_x_id_1',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='start_x_id_2',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='start_y_id_1',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='start_y_id_2',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='start_z_id_1',
        ),
        migrations.RemoveField(
            model_name='contactmodel',
            name='start_z_id_2',
        ),
    ]
