# Generated by Django 5.0.6 on 2025-04-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0021_rename_end_x_id_1_contactmodel_x_id_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelsmodel',
            name='arvId',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='travelsmodel',
            name='levId',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='visitmodel',
            name='arvT',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='visitmodel',
            name='levT',
            field=models.FloatField(),
        ),
    ]
