# Generated by Django 5.0.6 on 2025-04-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0022_alter_travelsmodel_arvid_alter_travelsmodel_levid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelsmodel',
            name='arvId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='travelsmodel',
            name='levId',
            field=models.IntegerField(),
        ),
    ]
