# Generated by Django 5.0.6 on 2025-04-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0023_alter_travelsmodel_arvid_alter_travelsmodel_levid'),
    ]

    operations = [
        migrations.AddField(
            model_name='configmodel',
            name='file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configmodel',
            name='isGeographicalCoordinates',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
