# Generated by Django 5.0.6 on 2025-04-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0024_configmodel_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configmodel',
            name='file',
        ),
    ]
