# Generated by Django 5.0.6 on 2025-04-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0025_remove_configmodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalmetricsmodel',
            name='occupied_quadrants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metricsmodel',
            name='occupied_quadrants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quadrantentropymodel',
            name='entity_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quadrantentropymodel',
            name='occupied_quadrants',
            field=models.IntegerField(null=True),
        ),
    ]
