# Generated by Django 5.2 on 2025-05-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0026_globalmetricsmodel_occupied_quadrants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staypointmodel',
            name='importanceDegree',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staypointmodel',
            name='totalVisitsTime',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
