# Generated by Django 5.2 on 2025-05-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0026_globalmetricsmodel_occupied_quadrants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalmetricsmodel',
            name='mobility_profile',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
