# Generated by Django 5.0.6 on 2025-05-12 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0027_staypointmodel_importancedegree_and_more'),
        ('metrics', '0028_globalmetricsmodel_trajectory_correlation'),
    ]

    operations = [
    ]
