# Generated by Django 5.0.6 on 2025-05-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0030_journeymodel_delete_travelsmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeymodel',
            name='journey_avg_speed',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
