# Generated by Django 5.0.6 on 2025-05-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0031_journeymodel_journey_avg_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalmetricsmodel',
            name='speed_variation_coefficient',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
